import { defineConfig, defineCollection, s } from 'velite'
import rehypeShiki from '@shikijs/rehype'
import remarkGfm from 'remark-gfm'

const posts = defineCollection({
  name: 'Post',
  pattern: 'posts/**/*.mdx',
  schema: s.object({
    title: s.string().max(99),
    date: s.isodate(),
    summary: s.excerpt(),
    content: s.mdx(),
    toc: s.toc(),
    metadata: s.metadata(),
    tags: s.array(s.string()).min(1),
    category: s.string(),
    draft: s.boolean().default(false),
    slug: s.slug('posts'),
  }),
})

export default defineConfig({
  root: 'content',
  output: {
    data: '.velite',
    assets: 'public/static',
    base: '/static/',
    clean: false,
    format: 'esm',
  },
  collections: { posts },
  markdown: {
    gfm: true,
    remarkPlugins: [remarkGfm],
    rehypePlugins: [],
  },
  mdx: {
    gfm: true,
    remarkPlugins: [remarkGfm],
    rehypePlugins: [
      [rehypeShiki, {
        theme: 'github-dark',
        grid: true,
      }],
    ],
  },
  complete: async () => {
    // Rewrite index.js to be Turbopack-compatible (inline JSON instead of import assertion)
    const fs = await import('fs/promises')
    const path = await import('path')
    const postsJson = await fs.readFile(path.join('.velite', 'posts.json'), 'utf-8')
    const indexJs = [
      '// This file is generated by Velite (patched for Turbopack compatibility)',
      `export const posts = ${postsJson};`,
    ].join('\n')
    await fs.writeFile(path.join('.velite', 'index.js'), indexJs)
  },
})
